#spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    database-platform: org.hibernate.dialect.MySQL5Dialect
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://momoko.es:3306/momokoBD
#    username: root
#  http:
#    multipart:
#      max-file-size: 10MB
#      max-request-size: 10MB
#  thymeleaf:
#    prefix: classpath:/templates
#
#security:
#  basic:
#    enabled: false
#  oauth2:
#    client:
#      clientId: 1932678757049258
#      clientSecret: 09417a8676c99ad9fd9cec4f06725f49
#      accessTokenUri: https://graph.facebook.com/oauth/access_token
#      userAuthorizationUri: https://www.facebook.com/dialog/oauth
#      tokenName: oauth_token
#      authenticationScheme: query
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: https://graph.facebook.com/me?fields=email,name
#      filter-order: 3
#
#server:
#  port: 5000
#  session:
#    timeout: 28800
#
##Google
#gmail:
#  client:
#    clientId: 720469847940-k8urpge03m9cn055mhi4mae4nn1p843m.apps.googleusercontent.com
#    clientSecret: jgwe1NMipdo79Mfwkjd08WiW
#    accessTokenUri: https://www.googleapis.com/oauth2/v3/token
#    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
#    clientAuthenticationScheme: query
#    scope: profile email
#  resource:
#    userInfoUri: https://www.googleapis.com/plus/v1/people/me
#    preferTokenInfo: false
#
#facebook:
#  client:
#    clientId: 233668646673605
#    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
#    accessTokenUri: https://graph.facebook.com/oauth/access_token
#    userAuthorizationUri: https://www.facebook.com/dialog/oauth
#    tokenName: oauth_token
#    authenticationScheme: query
#    clientAuthenticationScheme: form
#  resource:
#    userInfoUri: https://graph.facebook.com/me
#
##Facebook
##facebook:
##  client:
##    clientId: 1932678757049258
##    clientSecret: 5631874010ff42582ee3bf7a642bec6a
##    accessTokenUri: https://graph.facebook.com/oauth/access_token
##    userAuthorizationUri: https://www.facebook.com/dialog/oauth
##    tokenName: oauth_token
##    authenticationScheme: query
##    clientAuthenticationScheme: form
##  resource:
##    userInfoUri: https://graph.facebook.com/me
#
##AuthoritationServer
#
##security:
##  oauth2:
##    client:
##      client-id: acme
##      client-secret: acmepass
##      scope: read,write
##      auto-approve-scopes: '.*'
#
#logging:
#  level:
#    org:
#      springframework:
#        security: INFO
#      hibernate:
#        type: INFO
#        SQL: INFO
#    root: INFO
#
#
##momoko properties
#momokoConfiguracion:
#  esServidorLocal: false
#  imagenDefault: imagenes-destacadas/generica-libreria.jpg
#  directorios:
#    remote:
#      urlSitemap: https://www.momoko.es
#      urlFiles: https://www.momoko.es/images
#      urlImages: https://www.momoko.es/images/
#      urlUpload: https://www.momoko.es/
#      urlTemplates: https://www.momoko.es/templates/
#    local:
#      urlSitemap: https://www.momoko.es
#      urlFiles: https://www.momoko.es/images
#      urlImages: https://www.momoko.es/images/
#      urlTemplates: https://www.momoko.es/templates/
#      urlUpload: https://www.momoko.es/