export enum FilterRuleType {
  BOOLEAN = 'BOOLEAN',
  BETWEEN = 'BETWEEN',
  GREATER_THAN = 'GREATER_THAN',
  LESS_THAN = 'LESS_THAN',
  EQUAL = 'EQUAL',
  ENUM = 'ENUM',
  CONTAINS = 'CONTAINS',
  ALL_VALUES = 'ALL_VALUES'
}
