spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/momokobd2
    username: root

#server:
#  port: 9999
#  context-path: /client
#security:
#  oauth2:
#    client:
#      client-id: acme
#      client-secret: secret
#      access-token-uri: http://localhost:8080/oauth/token
#      user-authorization-uri: http://localhost:8080/oauth/authorize
#    resource:
#      user-info-uri: http://localhost:8080/me