export const environment = {
  production: false,

  log: true,

    // URLS app
    momokoUrl: 'https://momoko.es/',
    serverUrl : 'https://momoko.es/',
    uploadUrl : 'https://momoko.es/modelo/upload',
    urlFiles : 'https://momoko.es/images/',
    entradasUrl: 'https://momoko.es/modelo/entradas',
    librosUrl :  'https://momoko.es/modelo/libros',
    generosUrl :  'https://momoko.es/modelo/generos',
    addEntradaUrl: 'https://momoko.es/modelo/entradas/add',
    addLibroUrl :  'https://momoko.es/modelo/libros/add',
    addGeneroUrl :  'https://momoko.es/modelo/generos/add',
    informacionGeneralUrl:  'https://momoko.es/modelo/informacionGeneral',
    singUpURL: 'https://momoko.es/account/signup',
    oauthTokenUrl: 'https://momoko.es/oauth/token',
    accountTokenUrl: 'https://momoko.es/account/token',
    getEntradaUrl: 'https://momoko.es/public/entrada/',
    getEntradaAdminUrl: 'https://momoko.es/modelo/entrada/',
    indexDataUrl: 'https://momoko.es/public/indexData',
    obtenerLibroUrl: 'https://momoko.es/public/libro/',
    addComentarioUrl: 'https://momoko.es/public/comentario/add',
    obtenerVideoUrl: 'https://momoko.es/public/video/',
    getGeneroUrl: 'https://momoko.es/public/genero/',
    initDataUrl: 'https://momoko.es/public/initData/',
    addGaleriaUrl: 'https://momoko.es/modelo/galerias/add',
    galeriasUrl: 'https://momoko.es/modelo/galerias',
    getCategoriaUrl: 'https://momoko.es/public/categoria/',
    getEtiquetaUrl: 'https://momoko.es/public/etiqueta/',
    getNoticiasLibroUrl: 'https://momoko.es/public/noticias-libro/',
    suscripcionUrl: 'https://momoko.es/public/suscribirse/',
    sagasUrl: 'https://momoko.es/modelo/sagas',
    obtenerSagaAdmin: 'https://momoko.es/modelo/saga/',
    addSagaUrl: 'https://momoko.es/modelo/sagas/add',
    getSagaUrl: 'https://momoko.es/public/saga/',
    redactoresUrl: 'https://momoko.es/modelo/redactores'
};
