spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/momokobd
    username: root
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      

    
#Google
gmail:
  client:
    clientId: 720469847940-k8urpge03m9cn055mhi4mae4nn1p843m.apps.googleusercontent.com
    clientSecret: jgwe1NMipdo79Mfwkjd08WiW
    accessTokenUri: https://www.googleapis.com/oauth2/v3/token
    userAuthorizationUri: https://accounts.google.com/o/oauth2/auth
    clientAuthenticationScheme: query
    scope: profile email
  resource:
    userInfoUri: https://www.googleapis.com/plus/v1/people/me
    preferTokenInfo: false



#Facebook
facebook:
  client:
    clientId: 1932678757049258
    clientSecret: 5631874010ff42582ee3bf7a642bec6a
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

#AuthoritationServer  

#security:
#  oauth2:
#    client:
#      client-id: acme
#      client-secret: acmepass
#      scope: read,write
#      auto-approve-scopes: '.*'
      
logging:
  level:
    org.springframework.security: DEBUG
    
#momoko properties
momokoConfiguracion:
  directorios:
    urlFiles: D:/XAMPP/htdocs/images
    test: hola